---
apiVersion: v1
kind: Namespace
metadata:
  name: inhabit
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: inhabit
  name: web-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-server-inhabit
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-server-inhabit
    spec:
      containers:
      - image:  
        imagePullPolicy: Always
        name: web-server-inhabit
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  namespace: inhabit
  name: nginx
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-damier-inhabit
